/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as ApiShareTokenRouteImport } from './routes/api/share/$token'
import { Route as ApiDriveUploadsRouteImport } from './routes/api/drive/uploads'
import { Route as ApiDriveShareRouteImport } from './routes/api/drive/share'
import { Route as ApiDriveFoldersRouteImport } from './routes/api/drive/folders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDriveShareShareIdRouteImport } from './routes/api/drive/share/$shareId'
import { Route as ApiDriveFoldersFolderIdRouteImport } from './routes/api/drive/folders/$folderId'
import { Route as ApiDriveFilesFileIdRouteImport } from './routes/api/drive/files/$fileId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareTokenRoute = ApiShareTokenRouteImport.update({
  id: '/api/share/$token',
  path: '/api/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveUploadsRoute = ApiDriveUploadsRouteImport.update({
  id: '/api/drive/uploads',
  path: '/api/drive/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveShareRoute = ApiDriveShareRouteImport.update({
  id: '/api/drive/share',
  path: '/api/drive/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFoldersRoute = ApiDriveFoldersRouteImport.update({
  id: '/api/drive/folders',
  path: '/api/drive/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveShareShareIdRoute = ApiDriveShareShareIdRouteImport.update({
  id: '/$shareId',
  path: '/$shareId',
  getParentRoute: () => ApiDriveShareRoute,
} as any)
const ApiDriveFoldersFolderIdRoute = ApiDriveFoldersFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => ApiDriveFoldersRoute,
} as any)
const ApiDriveFilesFileIdRoute = ApiDriveFilesFileIdRouteImport.update({
  id: '/api/drive/files/$fileId',
  path: '/api/drive/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/drive': typeof DriveRoute
  '/shared': typeof SharedRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRoutesByTo {
  '/drive': typeof DriveRoute
  '/shared': typeof SharedRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/drive': typeof DriveRoute
  '/shared': typeof SharedRoute
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/drive'
    | '/shared'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/drive'
    | '/shared'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  id:
    | '__root__'
    | '/drive'
    | '/shared'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DriveRoute: typeof DriveRoute
  SharedRoute: typeof SharedRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDriveFoldersRoute: typeof ApiDriveFoldersRouteWithChildren
  ApiDriveShareRoute: typeof ApiDriveShareRouteWithChildren
  ApiDriveUploadsRoute: typeof ApiDriveUploadsRoute
  ApiShareTokenRoute: typeof ApiShareTokenRoute
  ApiDriveFilesFileIdRoute: typeof ApiDriveFilesFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$token': {
      id: '/api/share/$token'
      path: '/api/share/$token'
      fullPath: '/api/share/$token'
      preLoaderRoute: typeof ApiShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/uploads': {
      id: '/api/drive/uploads'
      path: '/api/drive/uploads'
      fullPath: '/api/drive/uploads'
      preLoaderRoute: typeof ApiDriveUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/share': {
      id: '/api/drive/share'
      path: '/api/drive/share'
      fullPath: '/api/drive/share'
      preLoaderRoute: typeof ApiDriveShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/folders': {
      id: '/api/drive/folders'
      path: '/api/drive/folders'
      fullPath: '/api/drive/folders'
      preLoaderRoute: typeof ApiDriveFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/share/$shareId': {
      id: '/api/drive/share/$shareId'
      path: '/$shareId'
      fullPath: '/api/drive/share/$shareId'
      preLoaderRoute: typeof ApiDriveShareShareIdRouteImport
      parentRoute: typeof ApiDriveShareRoute
    }
    '/api/drive/folders/$folderId': {
      id: '/api/drive/folders/$folderId'
      path: '/$folderId'
      fullPath: '/api/drive/folders/$folderId'
      preLoaderRoute: typeof ApiDriveFoldersFolderIdRouteImport
      parentRoute: typeof ApiDriveFoldersRoute
    }
    '/api/drive/files/$fileId': {
      id: '/api/drive/files/$fileId'
      path: '/api/drive/files/$fileId'
      fullPath: '/api/drive/files/$fileId'
      preLoaderRoute: typeof ApiDriveFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDriveFoldersRouteChildren {
  ApiDriveFoldersFolderIdRoute: typeof ApiDriveFoldersFolderIdRoute
}

const ApiDriveFoldersRouteChildren: ApiDriveFoldersRouteChildren = {
  ApiDriveFoldersFolderIdRoute: ApiDriveFoldersFolderIdRoute,
}

const ApiDriveFoldersRouteWithChildren = ApiDriveFoldersRoute._addFileChildren(
  ApiDriveFoldersRouteChildren,
)

interface ApiDriveShareRouteChildren {
  ApiDriveShareShareIdRoute: typeof ApiDriveShareShareIdRoute
}

const ApiDriveShareRouteChildren: ApiDriveShareRouteChildren = {
  ApiDriveShareShareIdRoute: ApiDriveShareShareIdRoute,
}

const ApiDriveShareRouteWithChildren = ApiDriveShareRoute._addFileChildren(
  ApiDriveShareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DriveRoute: DriveRoute,
  SharedRoute: SharedRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDriveFoldersRoute: ApiDriveFoldersRouteWithChildren,
  ApiDriveShareRoute: ApiDriveShareRouteWithChildren,
  ApiDriveUploadsRoute: ApiDriveUploadsRoute,
  ApiShareTokenRoute: ApiShareTokenRoute,
  ApiDriveFilesFileIdRoute: ApiDriveFilesFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
