/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DriveLayoutRouteImport } from './routes/drive/_layout'
import { Route as DriveLayoutIndexRouteImport } from './routes/drive/_layout/index'
import { Route as DriveLayoutSharedRouteImport } from './routes/drive/_layout/shared'
import { Route as DriveLayoutSplatRouteImport } from './routes/drive/_layout/$'
import { Route as ApiShareTokenRouteImport } from './routes/api/share/$token'
import { Route as ApiDriveUploadsRouteImport } from './routes/api/drive/uploads'
import { Route as ApiDriveShareRouteImport } from './routes/api/drive/share'
import { Route as ApiDriveListingRouteImport } from './routes/api/drive/listing'
import { Route as ApiDriveFoldersRouteImport } from './routes/api/drive/folders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDriveShareShareIdRouteImport } from './routes/api/drive/share/$shareId'
import { Route as ApiDriveFoldersFolderIdRouteImport } from './routes/api/drive/folders/$folderId'
import { Route as ApiDriveFilesFileIdRouteImport } from './routes/api/drive/files/$fileId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveLayoutRoute = DriveLayoutRouteImport.update({
  id: '/drive/_layout',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveLayoutIndexRoute = DriveLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveLayoutRoute,
} as any)
const DriveLayoutSharedRoute = DriveLayoutSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DriveLayoutRoute,
} as any)
const DriveLayoutSplatRoute = DriveLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DriveLayoutRoute,
} as any)
const ApiShareTokenRoute = ApiShareTokenRouteImport.update({
  id: '/api/share/$token',
  path: '/api/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveUploadsRoute = ApiDriveUploadsRouteImport.update({
  id: '/api/drive/uploads',
  path: '/api/drive/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveShareRoute = ApiDriveShareRouteImport.update({
  id: '/api/drive/share',
  path: '/api/drive/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveListingRoute = ApiDriveListingRouteImport.update({
  id: '/api/drive/listing',
  path: '/api/drive/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFoldersRoute = ApiDriveFoldersRouteImport.update({
  id: '/api/drive/folders',
  path: '/api/drive/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveShareShareIdRoute = ApiDriveShareShareIdRouteImport.update({
  id: '/$shareId',
  path: '/$shareId',
  getParentRoute: () => ApiDriveShareRoute,
} as any)
const ApiDriveFoldersFolderIdRoute = ApiDriveFoldersFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => ApiDriveFoldersRoute,
} as any)
const ApiDriveFilesFileIdRoute = ApiDriveFilesFileIdRouteImport.update({
  id: '/api/drive/files/$fileId',
  path: '/api/drive/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/drive': typeof DriveLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/listing': typeof ApiDriveListingRoute
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/drive/$': typeof DriveLayoutSplatRoute
  '/drive/shared': typeof DriveLayoutSharedRoute
  '/drive/': typeof DriveLayoutIndexRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/listing': typeof ApiDriveListingRoute
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/drive/$': typeof DriveLayoutSplatRoute
  '/drive/shared': typeof DriveLayoutSharedRoute
  '/drive': typeof DriveLayoutIndexRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sign-in': typeof SignInRoute
  '/drive/_layout': typeof DriveLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/folders': typeof ApiDriveFoldersRouteWithChildren
  '/api/drive/listing': typeof ApiDriveListingRoute
  '/api/drive/share': typeof ApiDriveShareRouteWithChildren
  '/api/drive/uploads': typeof ApiDriveUploadsRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/drive/_layout/$': typeof DriveLayoutSplatRoute
  '/drive/_layout/shared': typeof DriveLayoutSharedRoute
  '/drive/_layout/': typeof DriveLayoutIndexRoute
  '/api/drive/files/$fileId': typeof ApiDriveFilesFileIdRoute
  '/api/drive/folders/$folderId': typeof ApiDriveFoldersFolderIdRoute
  '/api/drive/share/$shareId': typeof ApiDriveShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/drive'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/listing'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/drive/$'
    | '/drive/shared'
    | '/drive/'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/listing'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/drive/$'
    | '/drive/shared'
    | '/drive'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  id:
    | '__root__'
    | '/sign-in'
    | '/drive/_layout'
    | '/api/auth/$'
    | '/api/drive/folders'
    | '/api/drive/listing'
    | '/api/drive/share'
    | '/api/drive/uploads'
    | '/api/share/$token'
    | '/drive/_layout/$'
    | '/drive/_layout/shared'
    | '/drive/_layout/'
    | '/api/drive/files/$fileId'
    | '/api/drive/folders/$folderId'
    | '/api/drive/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignInRoute: typeof SignInRoute
  DriveLayoutRoute: typeof DriveLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDriveFoldersRoute: typeof ApiDriveFoldersRouteWithChildren
  ApiDriveListingRoute: typeof ApiDriveListingRoute
  ApiDriveShareRoute: typeof ApiDriveShareRouteWithChildren
  ApiDriveUploadsRoute: typeof ApiDriveUploadsRoute
  ApiShareTokenRoute: typeof ApiShareTokenRoute
  ApiDriveFilesFileIdRoute: typeof ApiDriveFilesFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/_layout': {
      id: '/drive/_layout'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/_layout/': {
      id: '/drive/_layout/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveLayoutIndexRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
    '/drive/_layout/shared': {
      id: '/drive/_layout/shared'
      path: '/shared'
      fullPath: '/drive/shared'
      preLoaderRoute: typeof DriveLayoutSharedRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
    '/drive/_layout/$': {
      id: '/drive/_layout/$'
      path: '/$'
      fullPath: '/drive/$'
      preLoaderRoute: typeof DriveLayoutSplatRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
    '/api/share/$token': {
      id: '/api/share/$token'
      path: '/api/share/$token'
      fullPath: '/api/share/$token'
      preLoaderRoute: typeof ApiShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/uploads': {
      id: '/api/drive/uploads'
      path: '/api/drive/uploads'
      fullPath: '/api/drive/uploads'
      preLoaderRoute: typeof ApiDriveUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/share': {
      id: '/api/drive/share'
      path: '/api/drive/share'
      fullPath: '/api/drive/share'
      preLoaderRoute: typeof ApiDriveShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/listing': {
      id: '/api/drive/listing'
      path: '/api/drive/listing'
      fullPath: '/api/drive/listing'
      preLoaderRoute: typeof ApiDriveListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/folders': {
      id: '/api/drive/folders'
      path: '/api/drive/folders'
      fullPath: '/api/drive/folders'
      preLoaderRoute: typeof ApiDriveFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/share/$shareId': {
      id: '/api/drive/share/$shareId'
      path: '/$shareId'
      fullPath: '/api/drive/share/$shareId'
      preLoaderRoute: typeof ApiDriveShareShareIdRouteImport
      parentRoute: typeof ApiDriveShareRoute
    }
    '/api/drive/folders/$folderId': {
      id: '/api/drive/folders/$folderId'
      path: '/$folderId'
      fullPath: '/api/drive/folders/$folderId'
      preLoaderRoute: typeof ApiDriveFoldersFolderIdRouteImport
      parentRoute: typeof ApiDriveFoldersRoute
    }
    '/api/drive/files/$fileId': {
      id: '/api/drive/files/$fileId'
      path: '/api/drive/files/$fileId'
      fullPath: '/api/drive/files/$fileId'
      preLoaderRoute: typeof ApiDriveFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DriveLayoutRouteChildren {
  DriveLayoutSplatRoute: typeof DriveLayoutSplatRoute
  DriveLayoutSharedRoute: typeof DriveLayoutSharedRoute
  DriveLayoutIndexRoute: typeof DriveLayoutIndexRoute
}

const DriveLayoutRouteChildren: DriveLayoutRouteChildren = {
  DriveLayoutSplatRoute: DriveLayoutSplatRoute,
  DriveLayoutSharedRoute: DriveLayoutSharedRoute,
  DriveLayoutIndexRoute: DriveLayoutIndexRoute,
}

const DriveLayoutRouteWithChildren = DriveLayoutRoute._addFileChildren(
  DriveLayoutRouteChildren,
)

interface ApiDriveFoldersRouteChildren {
  ApiDriveFoldersFolderIdRoute: typeof ApiDriveFoldersFolderIdRoute
}

const ApiDriveFoldersRouteChildren: ApiDriveFoldersRouteChildren = {
  ApiDriveFoldersFolderIdRoute: ApiDriveFoldersFolderIdRoute,
}

const ApiDriveFoldersRouteWithChildren = ApiDriveFoldersRoute._addFileChildren(
  ApiDriveFoldersRouteChildren,
)

interface ApiDriveShareRouteChildren {
  ApiDriveShareShareIdRoute: typeof ApiDriveShareShareIdRoute
}

const ApiDriveShareRouteChildren: ApiDriveShareRouteChildren = {
  ApiDriveShareShareIdRoute: ApiDriveShareShareIdRoute,
}

const ApiDriveShareRouteWithChildren = ApiDriveShareRoute._addFileChildren(
  ApiDriveShareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignInRoute: SignInRoute,
  DriveLayoutRoute: DriveLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDriveFoldersRoute: ApiDriveFoldersRouteWithChildren,
  ApiDriveListingRoute: ApiDriveListingRoute,
  ApiDriveShareRoute: ApiDriveShareRouteWithChildren,
  ApiDriveUploadsRoute: ApiDriveUploadsRoute,
  ApiShareTokenRoute: ApiShareTokenRoute,
  ApiDriveFilesFileIdRoute: ApiDriveFilesFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
